# Nome da aplicação
micronaut.application.name=gestaoAluguelVeiculos
micronaut.server.port=8081

# Configuração do Banco de Dados PostgreSQL
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/aluguel_carros
datasources.default.username=postgres
datasources.default.password=1234

# JPA / Hibernate
# REMOVIDO: schema-generate=CREATE_DROP (para não apagar os dados ao reiniciar)
jpa.default.properties.hibernate.hbm2ddl.auto=create

micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.default.allowed-origins=http://127.0.0.1:5500,http://localhost:5173
micronaut.server.cors.configurations.default.allowed-methods=GET,POST,PUT,DELETE
micronaut.server.cors.configurations.default.allowed-headers=Content-Type

